version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: 
          name: Print out hello message
          command: echo "A first hello"
      - run:
          name: Slee for 25 milliseconds
          command: sleep 25

